### ISSUE TITLE
Parcel-2 Compatibility

### ISSUE THREAD

**Issue by collegeimprovements** [edm00se/parcel-plugin-goodie-bag#17]
Parcel-2 got released few days back. And existing plugins are not compatible with it.
We are using Parcel for all our dev/prod workflows with only one plugin(goodie-bag).
Can we test/try this plugin with Parcel-2.0 with some modifications ?

Link: https://medium.com/@devongovett/parcel-2-0-0-alpha-1-is-here-8b160c6e3f7e

**Comment by edm00se** [comment]
Determining compatibility and needed changes for parcel v2 is definitely the next priority for this plugin. I’ll see if I can play with it a bit this week.

Once it’s ready for testing, I’ll publish it under a tag for install from npm, which will become the default once parcel is published at v2.0 for full release (not alpha or beta, etc).

**Comment by edm00se** [comment]
As of my last check with parcel v2 alpha, it doesn't work with my minimum repro (my [demo use case](https://github.com/edm00se/parcel-ie11-issue-demo)) in a modern browser, let alone be a good start for how to create the next version of this plugin. Additionally, the naming conventions for v2 plugins will require a name change.

As such, this repo will continue as a v1 plugin, I'll support it for v1, but will need to work up a separate, albeit incredibly similar, plugin for v2 compliance. I'll track that under issue #16

**Comment by edm00se** [comment]
Update: see [this comment](https://github.com/edm00se/parcel-plugin-goodie-bag/issues/18#issuecomment-803409442), basically this won't be turning into a v2 compatible plugin, but you can achieve the same outcome with a little minor effort.
