### ISSUE TITLE
Requirement that the entry html file be name index.html

### ISSUE THREAD

**Issue by Joe-Withey** [edm00se/parcel-plugin-goodie-bag#6]
First of all thank you for making this plugin public, it has been a great help.

I have made a couple of modifications to the code for my own purposes and would like to consider raising a PR. The changes include:

* Supporting multiple html entry files
* Polyfilling html files that are not named `index.html`

Why was it made a condition that you can only polyfill a file named `index.html`?

**Comment by edm00se** [comment]
Thanks, I'm glad it's useful.

The main reason is that I tend to use the PostHTML inclusion of other html partials via `require`, so I wanted to ensure it was just the entrypoint that was having the polyfills added to them, to avoid potentially duplicates. This may have been overly broad on my part.

After some brief toying with removing the `index.html` check in a demo repo, it looks like the changes you suggest should be fine. In fact, I tried a single entrypoint demo repo with your forked copy and it worked out just fine. I would be happy to accept a PR.

**Comment by Joe-Withey** [comment]
Sweet! :)
